//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlassCustomerSignup
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Mail { get; set; }
        public string PhoneNum { get; set; }
        public string Password { get; set; }
        public string BuildNo { get; set; }
        public string Landmark { get; set; }
        public string State { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string City { get; set; }
    }
}
