//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        public int Pid { get; set; }
        public string ProductName { get; set; }
        public string length { get; set; }
        public string breadth { get; set; }
        public string polish { get; set; }
        public string TotalPrice { get; set; }
        public string Mail { get; set; }
        public string mobileno { get; set; }
        public string UserName { get; set; }
        public string Sqft { get; set; }
        public string BuildingNo { get; set; }
        public string LandMark { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string OrderImage { get; set; }
        public string ProductType { get; set; }
    }
}
